function retmap = rc_RCSE_retmap_from_retfit(parms,r_offset,th_offset,cond_info,forward)
%function retmap = rc_RCSE_retmap_from_retfit(parms,r_offset,th_offset,cond_info,forward)
%
% Purpose: wrapper for rc_define_retmap_from_retfit
%
% Required Input:
%   parms: RCSE parms struct
%   r_offset: eccentricity offset
%   th_offset: polar angle offset
%   cond_info: condition information struct
%   forward: forward solution struct
%
% Created:  03/04/11 by Don Hagler
% Last Mod: 12/08/13 by Don Hagler
%

if ~mmil_check_nargs(nargin,5), return; end;

if isempty(cond_info), cond_info = parms.cond_info; end;

% define retmap
fprintf('%s: generating retmap from retfit results...\n',mfilename);
tic
retmap = rc_define_retmap_from_retfit(...
  parms.retfit_results,...
  'cond_info',cond_info,...
  'r_offset',r_offset,...
  'th_offset',th_offset,...
  'grid_offset_flag',parms.grid_offset_flag,...
  'ecc_width',parms.ecc_width,...
  'theta_width',parms.theta_width,...
  'r_max',parms.r_max,...
  'w_thresh',parms.w_thresh,...
  'single_vertex_flag',parms.single_vertex_flag,...
  'forward',forward,...
  'rf_sizes',parms.rf_sizes,...
  'rf_slopes',parms.rf_slopes,...
  'restrict_hemi_flag',parms.restrict_hemi_flag,...
  'restrict_uplow_flag',parms.restrict_uplow_flag,...
  'data_flag',parms.retfit_data_flag,...
  'stim_type',parms.stim_type,...
  'vf2ctx',parms.vf2ctx,...
  'nbrhds',parms.nbrhds,...
  'area_names',parms.area_names);
toc

