function [stim_labels,conds_contrast] = abcd_set_contrasts_mid()
%function [stim_labels,conds_contrast] = abcd_set_contrasts_mid()
%
% Purpose: create struct array specifying contrasts to perform for MID task
%
% Output:
%   conds_contrast: struct array containing these fields:
%     groupA: cell array containing first set of condition names
%     groupB: cell array containing second set of condition names
%     name: contrast name
%
% Created:  12/14/16 by Don Hagler
% Prev Mod: 12/14/16 by Don Hagler
% Last Mod: 10/12/17 by Dani Cornejo 
% 

conds_contrast = [];
stim_labels = [];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

condnames = {'large_reward','small_reward','large_loss','small_loss','neutral'};
stimnames = {'antic','pos_feedback','neg_feedback'};

names_contrast = {...
  'antic'...
  'pos_feedback'...
  'neg_feedback'...
  'antic_reward_vs_neutral'...
  'antic_loss_vs_neutral'...
  'antic_large_reward_vs_neutral'...
  'antic_small_reward_vs_neutral'...
  'antic_large_loss_vs_neutral'...
  'antic_small_loss_vs_neutral'...
  'antic_reward_vs_loss'...
  'antic_reward'...
  'antic_loss'...
  'antic_large_vs_small_reward'...
  'antic_large_vs_small_loss'...
  'antic_large_reward_vs_large_loss'...
  'antic_small_reward_vs_small_loss'...
  'reward_pos_vs_neg_feedback'...
  'loss_pos_vs_neg_feedback'...
  'large_reward_pos_vs_neg_feedback'...
  'small_reward_pos_vs_neg_feedback'...
  'large_loss_pos_vs_neg_feedback'...
  'small_loss_pos_vs_neg_feedback'...
  'neutral_pos_vs_neg_feedback'... 
}; 

groupA = {...
  {'small_reward_antic','large_reward_antic','small_loss_antic','large_loss_antic','neutral_antic'};...
  {'small_reward_pos_feedback','large_reward_pos_feedback','small_loss_pos_feedback','large_loss_pos_feedback','neutral_pos_feedback'};...
  {'small_reward_neg_feedback','large_reward_neg_feedback','small_loss_neg_feedback','large_loss_neg_feedback','neutral_neg_feedback'};...
  {'large_reward_antic','small_reward_antic'};...
  {'large_loss_antic','small_loss_antic'};...
  {'large_reward_antic'};...
  {'small_reward_antic'};...
  {'large_loss_antic'};...
  {'small_loss_antic'};...
  {'large_reward_antic','small_reward_antic'};...
  {'large_reward_antic','small_reward_antic'};...
  {'large_loss_antic','small_loss_antic'};...
  {'large_reward_antic'};...
  {'large_loss_antic'};...
  {'large_reward_antic'};...
  {'small_reward_antic'};...
  {'large_reward_pos_feedback','small_reward_pos_feedback'};...
  {'large_loss_pos_feedback','small_loss_pos_feedback'};...
  {'large_reward_pos_feedback'};...
  {'small_reward_pos_feedback'};...
  {'large_loss_pos_feedback'};...
  {'small_loss_pos_feedback'};...
  {'large_loss_neg_feedback','neutral_pos_feedback'};...
}; 

groupB = {...
  [];...
  [];...
  [];...
  {'neutral_antic'};...
  {'neutral_antic'};...
  {'neutral_antic'};...
  {'neutral_antic'};...
  {'neutral_antic'};...
  {'neutral_antic'};...
  {'large_loss_antic','small_loss_antic'};...
  [];...
  [];...
  {'small_reward_antic'};...
  {'small_loss_antic'};...
  {'large_loss_antic'};...
  {'small_loss_antic'};...
  {'large_reward_neg_feedback','small_reward_neg_feedback'};...
  {'large_loss_neg_feedback','small_loss_neg_feedback'};...
  {'large_reward_neg_feedback'};...
  {'small_reward_neg_feedback'};...
  {'large_loss_neg_feedback'};...
  {'small_loss_neg_feedback'};...
  {'neutral_neg_feedback'};...
}; 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

nconds = length(condnames);
nstims = length(stimnames);

stim_labels = {};
nevents = 0;
for i=1:nconds
  cond = condnames{i};
  for j=1:nstims
    stim = stimnames{j};
    nevents = nevents + 1;
    stim_labels{nevents} = sprintf('%s_%s',cond,stim);
  end;
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ncontrast = length(names_contrast);
for i=1:ncontrast
  conds_contrast(i).groupA = groupA{i};
  conds_contrast(i).groupB = groupB{i};
  conds_contrast(i).name = names_contrast{i};
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

