function iSASZ_effects_word_char_hgp(fcfg)

fprintf([fcfg.sbj_nme ': Starting initial effects work on %s \n'],fcfg.sbj_nme)

cfg = [];
cfg.load    = 'yes';
cfg.file    = [fcfg.dat_fld '/' fcfg.sbj_nme '_overall_data.mat'];
bcc_dat     = ft_func([],cfg);

for iF = 1:numel(bcc_dat.data_name); 
    bcc_dat.(bcc_dat.data_name{iF}).cfg.alt_lab.stt_lab = bcc_dat.(bcc_dat.data_name{iF}).label; 
    bcc_dat.(bcc_dat.data_name{iF}).cfg.alt_lab.label = bcc_dat.(bcc_dat.data_name{iF}).label;
end

%% Orthographic Effects
if any(bcc_dat.(bcc_dat.data_name{1}).cfg.alt_eve.trialinfo<10)
    
cfg = [];
cfg.ovr_wrt = 1;
cfg.clr_fld = fcfg.clr_fld;

cfg.data_name = 2;

cfg.stt_lab = 'stt_lab';

cfg.alt_stt = { 'vis_lng_stt' ... 
                'vis_lng_big_stt' ...
                'vis_lng_frq_stt' ... 
                'vis_lng_ngh_stt' ...
                'vis_big_stt' ... 
                'vis_big_lng_stt' ...
                'vis_big_frq_stt' ... 
                'vis_big_ngh_stt' ...
                'vis_frq_stt' ... 
                'vis_frq_lng_stt' ...
                'vis_frq_big_stt' ... 
                'vis_frq_ngh_stt' ...
                'vis_ngh_stt' ... 
                'vis_ngh_lng_stt' ...
                'vis_ngh_big_stt' ...
                'vis_ngh_frq_stt' };
cfg.cmp_trl = { 'vis_lng_med' ... 
                'vis_lng_med_crr_by_vis_big' ...
                'vis_lng_med_crr_by_vis_frq' ...
                'vis_lng_med_crr_by_vis_ngh' ...
                'vis_big_med' ...
                'vis_big_med_crr_by_vis_lng' ...
                'vis_big_med_crr_by_vis_frq' ...
                'vis_big_med_crr_by_vis_ngh' ...
                'vis_frq_med' ...
                'vis_frq_med_crr_by_vis_lng' ...
                'vis_frq_med_crr_by_vis_big' ...
                'vis_frq_med_crr_by_vis_ngh' ...
                'vis_ngh_med' ...
                'vis_ngh_med_crr_by_vis_lng' ...
                'vis_ngh_med_crr_by_vis_big' ...
                'vis_ngh_med_crr_by_vis_frq' };
cfg.cmp_stt = { [1  1] ... 
                [2  2] ...
                [3  3] ... 
                [4  4] ...
                [5  5] ... 
                [6  6] ...
                [7  7] ... 
                [8  8] ...
                [9  9] ... 
                [10 10] ...
                [11 11] ... 
                [12 12] ...
                [13 13] ... 
                [14 14] ...
                [15 15] ... 
                [16 16] };
cfg.cmp_nme = { { 'Short' 'Long' } ; ... 
                { 'Short' 'Long' } ; ...
                { 'Short' 'Long' } ; ... 
                { 'Short' 'Long' } ; ...
                { 'Lower' 'Higher' } ; ... 
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ... 
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } };
cfg.cmp     = { { '131>132' '131<132' } ... 
                { '131>132' '131<132' } ...
                { '131>132' '131<132' } ... 
                { '131>132' '131<132' } ...
                { '141>142' '141<142' } ... 
                { '141>142' '141<142' } ...
                { '141>142' '141<142' } ... 
                { '141>142' '141<142' } ...
                { '151>152' '151<152' } ... 
                { '151>152' '151<152' } ...
                { '151>152' '151<152' } ... 
                { '151>152' '151<152' } ...
                { '161>162' '161<162' } ... 
                { '161>162' '161<162' } ...
                { '161>162' '161<162' } ... 
                { '161>162' '161<162' } };
cfg.tme_win = { { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } };
cfg.stt_col = { { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } };
           
cfg.sbj_nme  = fcfg.sbj_nme;
cfg.typ      = cellfun(@(x) x(end-2:end),bcc_dat.data_name(2),'uni',0);
if any(strcmpi(cfg.typ,'hlb')); cfg.typ(strcmpi(cfg.typ,'hlb')) = {'hgp'}; end
cfg.specific = {'typ' ; 1:numel(cfg.typ)};

dat          = ft_func(@mmil_chn_eff,cfg,bcc_dat);

% Split effects into ecog/depth
cfg = [];

cfg.sbj_nme = fcfg.sbj_nme;
cfg.clr_fld = fcfg.clr_fld;

cfg.dat_typ = {'hgp'};

mmil_split_stat(cfg);

% Split timing into ecog/depth
cfg = [];

cfg.sbj_nme = fcfg.sbj_nme;
cfg.clr_fld = fcfg.clr_fld;

cfg.dat_typ = {'hgp'};

mmil_split_timing(cfg);

end

%% Phonetic Stats
if any(bcc_dat.(bcc_dat.data_name{1}).cfg.alt_eve.trialinfo>10)
    
cfg = [];
cfg.ovr_wrt = 1;
cfg.clr_fld = fcfg.clr_fld;

cfg.data_name = 2;

cfg.stt_lab = 'stt_lab';

cfg.alt_stt = { 'aud_lng_stt' ... 
                'aud_lng_big_stt' ...
                'aud_lng_frq_stt' ... 
                'aud_lng_ngh_stt' ...
                'aud_big_stt' ... 
                'aud_big_lng_stt' ...
                'aud_big_frq_stt' ... 
                'aud_big_ngh_stt' ...
                'aud_frq_stt' ... 
                'aud_frq_lng_stt' ...
                'aud_frq_big_stt' ... 
                'aud_frq_ngh_stt' ...
                'aud_ngh_stt' ... 
                'aud_ngh_lng_stt' ...
                'aud_ngh_big_stt' ...
                'aud_ngh_frq_stt' };
cfg.cmp_trl = { 'aud_lng_med' ... 
                'aud_lng_med_crr_by_aud_big' ...
                'aud_lng_med_crr_by_aud_frq' ...
                'aud_lng_med_crr_by_aud_ngh' ...
                'aud_big_med' ...
                'aud_big_med_crr_by_aud_lng' ...
                'aud_big_med_crr_by_aud_frq' ...
                'aud_big_med_crr_by_aud_ngh' ...
                'aud_frq_med' ...
                'aud_frq_med_crr_by_aud_lng' ...
                'aud_frq_med_crr_by_aud_big' ...
                'aud_frq_med_crr_by_aud_ngh' ...
                'aud_ngh_med' ...
                'aud_ngh_med_crr_by_aud_lng' ...
                'aud_ngh_med_crr_by_aud_big' ...
                'aud_ngh_med_crr_by_aud_frq' };
cfg.cmp_stt = { [1  1] ... 
                [2  2] ...
                [3  3] ... 
                [4  4] ...
                [5  5] ... 
                [6  6] ...
                [7  7] ... 
                [8  8] ...
                [9  9] ... 
                [10 10] ...
                [11 11] ... 
                [12 12] ...
                [13 13] ... 
                [14 14] ...
                [15 15] ... 
                [16 16] };
cfg.cmp_nme = { { 'Short' 'Long' } ; ... 
                { 'Short' 'Long' } ; ...
                { 'Short' 'Long' } ; ... 
                { 'Short' 'Long' } ; ...
                { 'Lower' 'Higher' } ; ... 
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ... 
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } ; ...
                { 'Lower' 'Higher' } };
cfg.cmp     = { { '231>232' '231<232' } ... 
                { '231>232' '231<232' } ...
                { '231>232' '231<232' } ... 
                { '231>232' '231<232' } ...
                { '241>242' '241<242' } ... 
                { '241>242' '241<242' } ...
                { '241>242' '241<242' } ... 
                { '241>242' '241<242' } ...
                { '251>252' '251<252' } ... 
                { '251>252' '251<252' } ...
                { '251>252' '251<252' } ... 
                { '251>252' '251<252' } ...
                { '261>262' '261<262' } ... 
                { '261>262' '261<262' } ...
                { '261>262' '261<262' } ... 
                { '261>262' '261<262' } };
cfg.tme_win = { { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } ...
                { [0.025 0.800] [0.025 0.800] } ... 
                { [0.025 0.800] [0.025 0.800] } };
cfg.stt_col = { { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } ...
                { '' '' } ... 
                { '' '' } };
           
cfg.sbj_nme  = fcfg.sbj_nme;
cfg.typ      = cellfun(@(x) x(end-2:end),bcc_dat.data_name(2),'uni',0);
if any(strcmpi(cfg.typ,'hlb')); cfg.typ(strcmpi(cfg.typ,'hlb')) = {'hgp'}; end
cfg.specific = {'typ' ; 1:numel(cfg.typ)};

dat          = ft_func(@mmil_chn_eff,cfg,bcc_dat);

% Split effects into ecog/depth
cfg = [];

cfg.sbj_nme = fcfg.sbj_nme;
cfg.clr_fld = fcfg.clr_fld;

cfg.dat_typ = {'hgp'};

mmil_split_stat(cfg);

% Split timing into ecog/depth
cfg = [];

cfg.sbj_nme = fcfg.sbj_nme;
cfg.clr_fld = fcfg.clr_fld;

cfg.dat_typ = {'hgp'};

mmil_split_timing(cfg);

end


end