

function ejk_fmri_extract_surf_nii(cfg)

if ~isfield(cfg,'grd_par'); cfg.grd_par = [ cfg.bld_dir '/' cfg.sbj_nme '_' cfg.fnc_mri_nme '_' 'Tstat' '_' cfg.mdl_fnc_nme ]; end
if ~isfield(cfg,'pre_fix'); cfg.pre_fix = [ cfg.out_dir '/' cfg.sbj_nme '_' cfg.fnc_mri_nme '_' cfg.fnc_mri_srf '_' 'Tstat' '_' cfg.mdl_fnc_nme ]; end

%% Clean up prior surfaces

%% 
cmd = '';
cmd = [cmd 'cd' ' ' cfg.out_dir ' ' ];
cmd = sprintf('%s\n',cmd);

lft_cmd     = [cmd '3dVol2Surf' ' ' ...
                   '-spec'   ' ' cfg.sma_dir '/' cfg.sma_fle_nme '_both.spec' ' ' ...
                   '-surf_A' ' ' cfg.sma_dir '/' 'lh.' cfg.fnc_mri_srf '.gii' ' ' ...
                   '-sv'     ' ' cfg.sma_dir '/' cfg.sma_fle_nme '_SurfVol.nii' ' ' ...
                   '-grid_parent' ' ' cfg.grd_par '.nii.gz' ' ' ... % '-grid_parent ' fcfg.bld_dir '/' fcfg.bld_sbj_nme '/' dta_loc '/' '''stats.' fcfg.bld_sbj_nme '+orig[' num2str(nme_hld) ']''' ' ' ...
                   '-map_func ' 'mask' ' ' ...
                   '-out_niml ' cfg.pre_fix '_' 'lhs.niml.dset' ];
out = unix(lft_cmd);

rgh_cmd     = [cmd '3dVol2Surf' ' ' ...
                   '-spec'   ' ' cfg.sma_dir '/' cfg.sma_fle_nme '_both.spec' ' ' ...
                   '-surf_A' ' ' cfg.sma_dir '/' 'rh.' cfg.fnc_mri_srf '.gii' ' ' ...
                   '-sv'     ' ' cfg.sma_dir '/' cfg.sma_fle_nme '_SurfVol.nii' ' ' ...
                   '-grid_parent' ' ' cfg.grd_par '.nii.gz' ' ' ... % '-grid_parent ' fcfg.bld_dir '/' fcfg.bld_sbj_nme '/' dta_loc '/' '''stats.' fcfg.bld_sbj_nme '+orig[' num2str(nme_hld) ']''' ' ' ...
                   '-map_func ' 'mask' ' ' ...
                   '-out_niml ' cfg.pre_fix '_' 'rhs.niml.dset' ];
out = unix(rgh_cmd);

end