function npy_out = ejk_convert_neuropsych(cfg,npy_inp)

%% Define table
% SS T  Z
npy_tbl = [ 19 80  3.00 ; ...
            18 77  2.67 ; ...
            17 73  2.33 ; ...
            16 70  2.00 ; ...
            15 67  1.67 ; ...
            14 63  1.33 ; ...
            13 60  1.00 ; ...
            12 57  0.67 ; ...
            11 53  0.33 ; ...
            10 50  0.00 ; ...
            9  47 -0.33 ; ...
            8  43 -0.67 ; ...
            7  40 -1.00 ; ...
            6  37 -1.33 ; ...
            5  33 -1.67 ; ...
            4  30 -2.00 ; ...
            3  27 -2.33 ; ...
            2  23 -2.67 ; ...
            1  20 -3.00 ];

%% Convert
npy_out = nan(numel(npy_inp) ,1);

switch cfg.typ
    case 'z_to_ss'
        for iS = 1:numel(npy_inp)
            if ~isnan(npy_inp(iS))
                sbj_prf_lvl = find(npy_inp(iS)>=npy_tbl(:,3));
                if isempty(sbj_prf_lvl); sbj_prf_lvl=size(npy_tbl,1); end
                npy_out(iS) = npy_tbl(sbj_prf_lvl(1),1);
            end
        end
     case 'ss_to_t'
        for iS = 1:numel(npy_inp)
            if ~isnan(npy_inp(iS))
                sbj_prf_lvl = find(npy_inp(iS)>=npy_tbl(:,1));
                if isempty(sbj_prf_lvl); sbj_prf_lvl=size(npy_tbl,2); end
                npy_out(iS) = npy_tbl(sbj_prf_lvl(1),2);
            end
        end   
    case 'z_to_t'
        for iS = 1:numel(npy_inp)
            if ~isnan(npy_inp(iS))
                sbj_prf_lvl = find(npy_inp(iS)>=npy_tbl(:,3));
                if isempty(sbj_prf_lvl); sbj_prf_lvl=size(npy_tbl,2); end
                npy_out(iS) = npy_tbl(sbj_prf_lvl(1),2);
            end
        end
end



end