
%%
fcfg = [];
fcfg.dta_loc = [ dta_dir '/' 'Total_Demographic_Clinical_Neurobiolgical_Data.csv' ];
fcfg.dta_col = 2;
[ tot_dta, tot_sbj, tot_col] = ejk_dta_frm( fcfg );

%% Workspace
% tot_col(cellfun(@isstr,tot_dta(1,:)))
% 
% unique(tot_dta(:,strcmpi(tot_col,'hnd')))
% tabulate(tot_dta(:,strcmpi(tot_col,'hnd')))
% 
% unique(tot_dta_rcd(:,strcmpi(tot_col,'mts')))
% tabulate(tot_dta_rcd(:,strcmpi(tot_col,'mts')))
% 
% [ tot_sbj tot_dta_rcd(:,strcmpi(tot_col,'mts'))]
% 
% tab_hld = tabulate(tot_dta_rcd(:,strcmpi(tot_col,'mts')));
% tab_hld(:,1)

%% Key
clear rcd_nme rcd_val
rcd_nme     = { 'sex' 'srg_sde' 'srg_typ' 'eng_out' 'lng_lat' 'sde_sze_ons' 'mts' 'eng_out' 'eng_out' 'lng_lat'};
rcd_nme_new = { ''    ''        ''        ''        ''        ''            ''    'I'       'I_II'    ''};
rcd_val{1} = { 0 'M' ; 1 'F' };
rcd_val{2} = { 'Left' 'L' ; 'Right' 'R' };
rcd_val{3} = { 'neuroablation (hippocampus & amygdala)'   'SLAH' ;
               'SLAH; clean up SLAH'                      'SLAH' ; ...
               'SLAH; second SLAH'                        'SLAH' ; ...
               'neuroablation (hippocampus & amygdala +)' 'SLAH' ; ...
               'SLAH; ablation of caveroma'               'SLAH' ; ...
               'ATL +'                                    'ATL'  ; ...
               'ATL & repair of encephalode'              'ATL'  ; ...
               'limited ATL (later RF ablation)'          'ATL'  };
rcd_val{4} = { '1 (1 year)'                           'I' ; ...
               '3A (1 year)'                          'III' ; ...
               '3 (1 year)'                           'III' ; ...
               '1A (1 year)'                          'I' ; ...
               'Missing'                              '' ; ...
               '2B (1 year)'                          'II' ; ...
               '2A (1 year)'                          'II' ; ...
               '1A (6 months)'                        'I' ; ...
               '4B (6 months); 2B after second SLAH'  'IV'
               '4A (6 months)'                        'IV' ; ...
               '2D (1 year)'                          'II' ; ...
               '2D (6 months)'                        'II' ; ...
               '4B (6 months); 2A after resection'    'IV' ; ...
               '2A (6 months)'                        'II' ; ...
               '3A (6 months); 3A after ATL'          'III' ; ...
               '1B (1 year)'                          'I' ; ...
               '1D (1 year)'                          'I' ; ...
               '4B (1 year)'                          'IV' ; ...
               '4 (1 year)'                           'IV' ; ...
               '2 (1 year)'                           'II' ; ...
               '1 (6 months)'                         'I' };
rcd_val{5} = { 3                                          'B' ; ...
               2                                          'L' ; ...
               1                                          'R' ; ...
               'Bilateral'                                'B' ; ...
               'Bilateral (L>R)'                          'B' ; ...
               'Left'                                     'L' ; ...
               'Left based on Wada; fMRI suggested Right' 'L' ; ...
               'Right'                                    'R' ; ...
               'Unknown'                                  '' };
rcd_val{6} = { 'Left' 'L' ; 'Right' 'R' };
rcd_val{7} = { 0     'no'  ; ... 
               1     'yes' ; ...
               'L'   'yes' ; ...
               'R'   'yes' ; ...
               'N/A' 'no'  ; ...
               ''    'no'};
rcd_val{8}  = { 'I' 'I' ; 'II' 'II+' ; 'III' 'II+' ; 'IV' 'II+'  };
rcd_val{9}  = { 'I' 'I_II' ; 'II' 'I_II' ; 'III' 'III_IV' ; 'IV' 'III_IV'  };
rcd_val{10}  = { 'L' 'L' ; 'R' 'Atypical' ; 'B' 'Atypical' }; %; 1 'Atypical' ; 2 'L' ; 3 'Atypical' 

%% Run
fcfg = [];

fcfg.dta     = tot_dta;
fcfg.dta_col = tot_col;

fcfg.rcd_nme = rcd_nme;
fcfg.rcd_nme_new = rcd_nme_new;
fcfg.rcd_val = rcd_val;

fcfg.swt_val = 1;

fcfg.frc_fll = { 'mts' };

[ tot_dta_rcd, tot_col_rcd ] = ejk_recode(fcfg);

%% Save out
cell2csv([ dta_dir '/' 'Total_Demographic_Clinical_Neurobiolgical_Data_recoded.csv' ] , [ 'sbj_nme' tot_col_rcd ; tot_sbj tot_dta_rcd]);


