#! /bin/sh
# (next line not seen by tcl) \
exec tclsh $0 ${1+"$@"}

if {$argc != 1} {
  puts "use: bls <backslashed-pattern-that-matches-too-many-for-csh>"
  return
}
foreach file [lsort [glob [lindex $argv 0]]] { puts $file }
