
%% ENIGMA-Epilepsy Codes
bid_nme_use = bid_nme{1};

% Put together (re-)codebook
cde_bok.(bid_nme_use).dx = { 0 'HC' ; ...
                             1 'EPD' ; ...
                             9 'other' };

cde_bok.(bid_nme_use).sex = { 1 'Male' ; ...
                              2 'Female' ; ...
                              3 'other' ; ...
                              4 'unknown'};

cde_bok.(bid_nme_use).handedness = { 1 'Right' ; ...
                                     2 'Left' ; ...
                                     3 'Ambi' ; ...
                                     4 'unknown'};


cde_bok.(bid_nme_use).sdx         = { 0	 'HC' ; ...
                                      2	 'GGE' ; ...
                                      3	 'TLE_MTS_L' ; ...
                                      4	 'TLE_MTS_R' ; ...
                                      5	 'TLE_L' ; ...
                                      6	 'TLE-R' ; ...
                                      7	 'extra_TLE_focal' ; ...
                                      8	 'unspecified' ; ...
                                      9	 'bilateral_TLE' ; ...
                                      10 'encephalopathy' };

cde_bok.(bid_nme_use).dx_epi_type = { 1 'focal' ; ...
                                      2 'generalized' ; ...
                                      3 'mixed' ; ...
                                      4 'unknown'};

cde_bok.(bid_nme_use).localization = { 1 'temporal' ; ...
                                       2 'temporal_plus' ; ...
                                       3 'ex-tle-frontal' ; ...
                                       4 'unknown'};

cde_bok.(bid_nme_use).lateralization = { 1 'right' ; ...
                                         2 'left' ; ...
                                         3 'bilateral' ; ...
                                         4 'multifocal' ; ...
                                         9 'unknown' };

cde_bok.(bid_nme_use).mts = { 0 'noHS' ; ...
                              1 'HS_mri' ; ...
                              2 'HS_pathology' ; ...
                              9 'unknown' };

cde_bok.(bid_nme_use).site = { 1  'CNH_ENIGMA' ; ...
                               2  'UniMore_ENIGMA' ; ...
                               3  'UDA_ENIGMA' ; ...
                               4  'Rush_ENIGMA' ; ...
                               5  'UniCa_ENIGMA' ; ...
                               6  'USZ_ENIGMA' ; ...
                               7  'UNICAMP_ENIGMA' ; ...
                               8  'GWU_ENIGMA' ; ...
                               9  'UCT_ENIGMA' ; ...
                               10 'Nanjing_ENIGMA' ; ...
                               11 'UCSD_ENIGMA' ; ...
                               12 'ULB_ENIGMA' ; ...
                               13 'EPICZ_ENIGMA' ; ...
                               14 'FSM_ENIGMA' ; ...
                               15 'Gottingen_ENIGMA' ; ...
                               16 'UKBonn_ENIGMA' ; ...
                               17 'MNI_ENIGMA' ; ...
                               18 'NYU_ENIGMA' ; ...
                               19 'IGG_ENIGMA' ; ...
                               20 'UNAM_ENIGMA' ; ...
                               21 'UCLA_ENIGMA' ; ...
                               22 'UPenn_ENIGMA' ; ...
                               23 'MUSC_ENIGMA' ; ...
                               24 'LNF_ENIGMA' ; ...
                               25 'Emory_ENIGMA' ; ...
                               26 'MeyerClinic_ENIGMA' ; ...
                               27 'Tübingen_ENIGMA' ; ...
                               28 'UCL_ENIGMA' ; ...
                               29 'Monash_ENIGMA' ; ...
                               30 'UniMe_ENIGMA' ; ...
                               31 'UCSF_ENIGMA' ; ...
                               32 'Frankfurt_ENIGMA' ; ...
                               33 'WULondonOntario_ENIGMA' ; ...
                               34 'UCalgary_ENIGMA' ; ...
                               35 'TLVMC_ENIGMA' ; ...
                               36 'BWH_ENIGMA' ; ...
                               99 'other_ENIGMA' };

%% ECP Codes
bid_nme_use = bid_nme{2};

% Put together (re-)codebook
cde_bok.(bid_nme_use).mri1coil = { 1 'ECP' };

cde_bok.(bid_nme_use).dx = { 0 'HC' ; ...
                             1 'EPD'};

cde_bok.(bid_nme_use).dx_loc = { 0 '' ; ...
                                 1 'temporal'};

cde_bok.(bid_nme_use).sex = { 1 'Female' ; ...
                              2 'Male'};

cde_bok.(bid_nme_use).ehq_classify = { 'R' 'Right' ; ...
                                       'L' 'Left' ; ...
                                       'B' 'Ambi' };

cde_bok.(bid_nme_use).tleside = { 1 'left' ; ...
                                  2 'right' ; ...
                                  3 'bilateral' };

cde_bok.(bid_nme_use).criteriontle4 = { 0 'noHS' ; ...
                                        1 'HS_mri' };

%% CAPES Codes




