function ts_freqanalysis_sample ()

data_dir     = ' ';                                   % study directory
subject      = ' ';                                   % suject name
epochfile    = ' ';                                   % name of the epoch file to use for frequency analysis

prefix         = ' ';                                 % prefix to give new timefrequency data
method         = 'wltconvol';                         % FieldTrip method for frequency analysis
foi            = [1:1:60];                            % process 1-60 Hz in 1Hz increments
toi            = [-200:1:1000];                       % time of interst is -200 to 1000 ms
width          = [1 1 1 linspace(1,15,length(4:60))]; % vary the width of the Morlet Wavelet
output         = 'pow'                                % output power
reject_flag    = 1;                                   % perform automatic rejection in time-frequency domain
baseline_start = -200;                                % baseline values used during rejection
baseline_end   = 0;
blthresh       = 5;                                   % threshold for rejecting a trial for baseline calculation
rejthresh      = 30;                                  % threshold for rejecting a trial 


%% Run Time Frequency Analysis

load(fullfile(data_dir,subject,'matfiles',epochfile));
outdir = fullfile(data_dir,subjects_dir);

ts_freqanalysis (epoch_data,...
      'prefix',prefix,...
      'outdir',outdir,...
      'method',method,...
      'foi'   ,foi,...
      'toi'   ,toi,...
      'width' ,width,...
      'output',output,...
      'reject_flag',reject_flag,...
      'baseline_start',baseline_start,...
      'baseline_end',baseline_end,...
      'blthresh',blthresh,...
      'rejthresh',rejthresh...
      );
