function SL_initial_plot_2(fcfg)

%% Initial Load
sbj  = fcfg.sbj_nme;

fprintf([fcfg.sbj_nme ': Starting initial stats work on %s \n'],sbj)

infile = [fcfg.out_pth '/' sbj '_overall_data.mat'];
outpath = fcfg.out_pth;

cfg = [];
cfg.load = 'yes';
cfg.file = [outpath '/' sbj '_overall_data.mat'];
sll_dat  = ft_func([],cfg);

for iD = 1:numel(sll_dat.data_name); 
    sll_dat.(sll_dat.data_name{iD}).cfg.alt_lab.stt_lab = sll_dat.(sll_dat.data_name{iD}).label; 
end

eme_col = distinguishable_colors(12);

%% Channel-by-Channel, 2x3 (VisNse/AudNse/Mtc x LFP/HGP)
for iD = 1:numel(sll_dat.data_name);
    
    fprintf('Starting work on %s \n',fcfg.sbj_nme)
    
    cfg           = [];
    
    cfg.type      = 'chan';
    cfg.lgd       = 0;
    
    cfg.dat       = {sll_dat.(sll_dat.data_name{iD})};
    
    cfg.plt_dim   = [4 4];
    cfg.dat_loc   = [ 1 1 1 0 ; ...
                      1 1 1 0 ; ...
                      1 1 1 0 ; ...
                      1 1 1 0 ];
    
    cfg.plt_lbl   = { 'Overall'            'Visual Bigram'       'Auditory Bigram' '' ; ...
                      'Visual Selective'   'Visual Word' ''      'Auditory Word' ; ...
                      'Auditory Selective' 'Visual Neighborhood' 'Auditory Neighborhood' '' ; ...
                      'Match/Mismatch'     'Ortheme'             'Phoneme' ''};
    cfg.ttl_num   = zeros(4,4);
    
    cfg.alt_eve   = {'ovr_all_eve' 'vis_big_med' 'aud_big_med' '' ; ...
                     'vis_tot_nse' 'vis_wrd'     'aud_wrd' '' ; ...
                     'aud_tot_nse' 'vis_ngh_med' 'aud_ngh_med' '' ;
                     'trialinfo'   'vis_con'     'aud_con' ''};
    cfg.eve       = {[101]     [121 122] [221 222] [] ; ...
                     [101 102] [101 102] [201 202] [] ; ...
                     [111 112] [131 132] [231 232] [] ; ...
                     [1 2]     [1:12]    [1:12] [] };
    
    cfg.std_err   = 1;
    cfg.lnstyle.col_ord = {{rgb('black')}                    {rgb('dark red') rgb('bright red')}            {rgb('dark blue') rgb('bright blue')} {} ; ...
                           {rgb('red') rgb('reddish grey')}  {rgb('bright red') rgb('dark red')}            {rgb('bright blue') rgb('dark blue')} {} ; ...
                           {rgb('blue') rgb('greyish blue')} {rgb('dark red') rgb('bright red')}            {rgb('dark blue') rgb('bright blue')} {} ; ...
                           {rgb('green') rgb('orange')}      mat2cell(eme_col,ones(1,size(eme_col,1)),3)'   mat2cell(eme_col,ones(1,size(eme_col,1)),3)' {} };
    cfg.cnd_nme         = {};
    
    cfg.stt_dat = { {'ovr_stt'}     {'vis_big_stt'} {'aud_big_stt'} {} ; ...
                    {'vis_nse_stt'} {'vis_wrd_stt'} {'aud_wrd_stt'} {} ; ...
                    {'aud_nse_stt'} {'vis_ngh_stt'} {'aud_ngh_stt'} {} ; ...
                    {'vis_mtc_stt'} {'vis_con_stt'} {'aud_con_stt'} {} };
    cfg.stt_col = { {ft_stt_col(rgb('grey'))}          {ft_stt_col(rgb('dark red'))}   {ft_stt_col(rgb('dark blue'))} {} ; ...
                    {ft_stt_col(rgb('reddish grey'))}  {ft_stt_col(rgb('dark red'))}   {ft_stt_col(rgb('dark blue'))} {} ; ...
                    {ft_stt_col(rgb('greyish blue'))}  {ft_stt_col(rgb('dark red'))}   {ft_stt_col(rgb('dark blue'))} {} ; ...
                    {ft_stt_col(rgb('greyish green'))} {ft_stt_col(rgb('bright red'))} {ft_stt_col(rgb('bright blue'))} {} };
    
    cfg.alt_lbl = 'label';
    cfg.stt_lab = 'stt_lab';
    
    cfg.y_lnk       = [1 1 1 0 ; 1 1 1 0 ; 1 1 1 0 ; 1 1 1 0 ];
    cfg.x_lim       = [-0.3 1.5];
    cfg.v_lne       = { [0.000 0.450] [0.000 0.450] [0.000 0.450] [] ; ...
                        [0.000 0.450] [0.000 0.450] [0.000 0.450] [] ; ...
                        [0.000 0.450] [0.000 0.450] [0.000 0.450] [] ; ...
                        [0.000 0.450] [0.000 0.450] [0.000 0.450] [] };
    cfg.v_lne_col   = {{rgb('red') rgb('blue')} {rgb('red') rgb('blue')} {rgb('red') rgb('blue')} {} ; ...
                       {rgb('red') rgb('blue')} {rgb('red') rgb('blue')} {rgb('red') rgb('blue')} {} ; ...
                       {rgb('red') rgb('blue')} {rgb('red') rgb('blue')} {rgb('red') rgb('blue')} {} ; ...
                       {rgb('red') rgb('blue')} {rgb('red') rgb('blue')} {rgb('red') rgb('blue')} {} };
    
    cfg.v_lne_wdt   = {[2 2] [2 2] [2 2] [] ; ...
                       [2 2] [2 2] [2 2] [] ; ...
                       [2 2] [2 2] [2 2] [] ; ...
                       [2 2] [2 2] [2 2] [] };
    cfg.axe_fnt_sze = [15 15 15 0 ; ...
                       15 15 15 0 ; ...
                       15 15 15 0 ; ...
                       15 15 15 0 ];
    cfg.axe_lne_sze = [3 3 3 0 ; ...
                       3 3 3 0 ; ...
                       3 3 3 0 ; ...
                       3 3 3 0 ];
    cfg.ttl_lne_sze = [36 36 36 0 ; ...
                       36 36 36 0 ; ...
                       36 36 36 0 ; ...
                       36 36 36 0 ];
    
    cfg.print      = 1;
    cfg.nofig      = 1;
    cfg.print_type = 'png';
    cfg.outdir     = [outpath '/' 'initial_plot' '/' fcfg.sbj_nme '/' sll_dat.data_name{iD}];
    cfg.prefix     = [fcfg.sbj_nme '_'];
    
    mmil_ieeg_sensor_plot_v5(cfg)
    
end

end