clear; clc;

%% Initial load
% UW database
fcfg = [];
fcfg.dta_loc = [ '/home/ekaestner/Dropbox/McDonald Lab/Erik/Projects/Imaging/fce_nme_emy/RedcapData' '/' 'UW_New_Total_Database.csv' ];
[ dta_wsh, dta_wsh_sbj, dta_wsh_col ] = ejk_dta_frm(fcfg);

sbj_ind = strcmpi(dta_wsh(:,strcmpi(dta_wsh_col,'time_point')),'T1');
dta_wsh = dta_wsh(sbj_ind,:);
dta_wsh_sbj = dta_wsh_sbj(sbj_ind,:);

% Redcap
fcfg = [];
fcfg.red_fle = [ '/home/ekaestne/PROJECTS/DATA/csv/redcap' '/' 'Redcap_2023_01_12.csv'];
fcfg.sep     = '|';
[sbj_dem , sbj_sze , sbj_scn , sbj_cog, sbj_emo, sbj_srg] = ejk_load_redcap(fcfg);

%% Fix UW Coding


%% Add together
add_dem = { 'sbj_scn_dte' 'date_of_visit' ; ...
            'sbj_grp'     'group'      ; ...
            'sbj_sex'     'Sex'        ; ...
            'sbj_hnd'     'handedness' ; 
            'sbj_age'     'age'        ; ...
            'sbj_edu'     'education'  };
        
sze_nme = { 'sbj_age_ons' 'age_of_seizure_onset'     ; ...
            'sbj_sde_ons' 'side_seizure_onset' ; ...
            'sbj_mts'     'MTS'   ; ...
            'sbj_aed_num' 'ASM#'  ; ...
            'sbj_aed_typ' 'ASMs'  }; 

cog_nme = { 'neu_psy_tst_dte'         'date_of_visit'                   ; ...
            'log_mem_raw_scr_one'     'WMS_IV_Logical_Memory_I_raw'     ; ...
            'log_mem_nor_scr_one'     'WMS_IV_Logical_Memory_I_scaled'  ; ...
            'log_mem_raw_scr_two'     'WMS_IV_Logical_Memory_II_raw'    ; ...
            'log_mem_nor_scr_two'     'WMS_IV_Logical_Memory_II_scaled' ; ...
            'vp1_raw_scr'             'WMS_IV_Verbal_Paired_Associates_I_raw' ; ...
            'vp1_nor_scr'             'WMS_IV_Verbal_Paired_Associates_I_scaled'  ; ...
            'vp2_raw_scr'             'WMS_IV_Verbal_Paired_Associates_II_raw'    ; ...
            'vp2_nor_scr'             'WMS_IV_Verbal_Paired_Associates_II_scaled' ; ...
            'bnt_raw_scr'             'BNT_with_semantic_cues_raw'                ; ...
            'bnt_nor_scr'             'BNT_with_semantic_cues_Tscore'             ; ...
            'wtr_int_raw_scr'         'wtar_raw'                        'nan'; ...
            'wtr_int_nor_scr'         'wtar_iq'                         'nan'; ...
            ''                        'fsiq'};       
        
emo_nme = { 'bdi'     'bdi_total_score' ; ...
            'bai'     'bai_total_score' };
        
srg_nme = { 'srg_typ' 'type_of_surgery' ; ...
            'eng_out' ''   ; ...
            'wda_lng' ''     };         
        
%% Combine        
fcfg = [];
fcfg.add_dta     = [];
fcfg.add_dta_col = [];
fcfg.add_dta_sbj = [];
fcfg.red_cap     = sbj_dem;
sbj_dem          = ejk_add_red_cap(fcfg);


 




