function fw_plot(fcfg)

%% Initial Load
sbj  = fcfg.sbj_nme;

fprintf([fcfg.sbj_nme ': Starting initial plots work on %s \n'],sbj)

infile = [fcfg.sbj_dat_hld '/' sbj '_overall_data.mat'];

cfg = [];
cfg.load = 'yes';
cfg.file = [fcfg.sbj_dat_hld '/' sbj '_overall_data.mat'];
fwv_dat  = ft_func([],cfg);

for iD = 1:numel(fwv_dat.data_name); 
    fwv_dat.(fwv_dat.data_name{iD}).cfg.alt_lab.stt_lab = fwv_dat.(fwv_dat.data_name{iD}).label; 
end

%% Channel-by-Channel, 2x3 (VisNse/AudNse/Mtc x LFP/HGP)
 for iD = 1:numel(fwv_dat.data_name);
    
    fprintf('Starting work on %s \n',fcfg.sbj_nme)
    
    cfg           = [];
    
    cfg.type      = 'chan';
    cfg.lgd       = 0;
    
    cfg.dat       = {fwv_dat.(fwv_dat.data_name{iD})};
    
    cfg.plt_dim   = [4 4];
    cfg.dat_loc   = [ 1 1 1 1 ; ...
                      1 1 1 0 ; ...
                      1 1 0 0 ; ...
                      1 1 0 0 ];
    
    cfg.plt_lbl   = { 'Stimuli'     'Word Length'       'NonWord Length'       'Overall' ; ...
                      'Letter/FF'   'Word Bigram'       'nwn_big_med'          '' ; ...
                      'Word/Letter' 'Word Frequency'    '' '' ; ...
                      'Old / New'   'Word Neighborhood' 'NonWord Neighborhood'                     ''};
    cfg.ttl_num   = zeros(4,4);
    
    cfg.alt_eve   = {'trialinfo' 'wrd_lng_med' 'nwn_lng_med' 'vis_ovr' ; ...
                     'trialinfo' 'wrd_big_med' 'nwn_big_med' '' ; ...
                     'trialinfo' 'wrd_frq_med' ''            '' ;
                     'trialinfo' 'wrd_ngh_med' '' ''};
    cfg.eve       = {[3 4 5 6] [111 112] [211 212] [101] ; ...
                     [5 6]     [141 142] [221 222] [] ; ...
                     [3 5]     [121 122] []        [] ; ...
                     [3 4]     [131 132] []        [] };
    
    cfg.std_err   = 1;
    cfg.lnstyle.col_ord = {{rgb('bright red') rgb('orange') rgb('red') rgb('grey')} {rgb('red') rgb('bright red')} {rgb('reddish grey') rgb('dark red')} {rgb('black')} ; ...
                           {rgb('red') rgb('grey')}                                 {rgb('red') rgb('bright red')} {rgb('reddish grey') rgb('dark red')} {} ; ...
                           {rgb('bright red') rgb('red')}                           {rgb('red') rgb('bright red')} {}                                    {} ; ...
                           {rgb('bright red') rgb('orange')}                        {rgb('red') rgb('bright red')} {}                                    {} };
    cfg.cnd_nme         = {};
    
    cfg.stt_dat = { {'vis_stm'} {'vis_wrd_lng'} {'vis_nwn_lng'} {'vis_ovr_stt'} ; ...
                    {'vis_ltr'} {'vis_wrd_big'} {'vis_nwn_big'} {''} ; ...
                    {'vis_wrd'} {'vis_wrd_frq'} {''}            {''} ; ...
                    {'vis_old'} {'vis_wrd_ngh'} {'vis_nwn_ngh'} {''} };
    cfg.stt_col = { {ft_stt_col(rgb('red'))}        {ft_stt_col(rgb('light red'))} {ft_stt_col(rgb('reddish grey'))} {ft_stt_col(rgb('grey'))} ; ...
                    {ft_stt_col(rgb('light red'))}  {ft_stt_col(rgb('light red'))} {ft_stt_col(rgb('reddish grey'))} {} ; ...
                    {ft_stt_col(rgb('bright red'))} {ft_stt_col(rgb('light red'))} {}                                {} ; ...
                    {ft_stt_col(rgb('orange'))}     {ft_stt_col(rgb('light red'))} {}                                {} };
    
    cfg.alt_lbl = 'label';
    cfg.stt_lab = 'stt_lab';
    
    cfg.y_lnk       = [1 1 1 1 ; 1 1 1 1 ; 1 1 1 1 ; 1 1 1 1 ];
    cfg.x_lim       = [-0.15 0.75];
    cfg.v_lne       = { [0.000 0.200 0.400] [0.000 0.200 0.400] [0.000 0.200 0.400] [0 0.200 0.400] ; ...
                        [0.000 0.200 0.400] [0.000 0.200 0.400] [0.000 0.200 0.400] [0 0.200 0.400] ; ...
                        [0.000 0.200 0.400] [0.000 0.200 0.400] [0.000 0.200 0.400] [0 0.200 0.400] ; ...
                        [0.000 0.200 0.400] [0.000 0.200 0.400] [0.000 0.200 0.400] [0 0.200 0.400] };
    cfg.v_lne_col   = {{rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} ; ...
                       {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} ; ...
                       {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} ; ...
                       {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} {rgb('black') rgb('black') rgb('black')} };
    
    cfg.v_lne_wdt   = {[2 2 2] [2 2 2] [2 2 2] [2 2 2] ; ...
                       [2 2 2] [2 2 2] [2 2 2] [2 2 2] ; ...
                       [2 2 2] [2 2 2] [2 2 2] [2 2 2] ; ...
                       [2 2 2] [2 2 2] [2 2 2] [2 2 2] };
    cfg.axe_fnt_sze = [15 15 15 15 ; ...
                       15 15 15 15 ; ...
                       15 15 15 15 ; ...
                       15 15 15 15 ];
    cfg.axe_lne_sze = [3 3 3 3 ; ...
                       3 3 3 3 ; ...
                       3 3 3 3 ; ...
                       3 3 3 3 ];
    cfg.ttl_lne_sze = [36 36 36 36 ; ...
                       36 36 36 36 ; ...
                       36 36 36 36 ; ...
                       36 36 36 36 ];
    
    cfg.print      = 1;
    cfg.nofig      = 1;
    cfg.print_type = 'png';
    cfg.outdir     = [fcfg.sbj_dat_hld '/' 'initial_plot' '/' fcfg.sbj_nme '/' fwv_dat.data_name{iD}];
    cfg.prefix     = [fcfg.sbj_nme '_'];
    
    mmil_ieeg_sensor_plot_v5(cfg)
    
end

end