function [sbj_dem , sbj_sze , sbj_scn , sbj_cog, sbj_emo, sbj_srg] = ejk_load_redcap_v2(cfg)
% cfg = [];
% cfg. [];
%
%
%
%
%

if ~isfield(cfg,'sep'); cfg.sep=','; end

%% Load Redcap
fcfg = [];
fcfg.red_fle = cfg.red_fle;
fcfg.sep     = cfg.sep;
sbj_hld = ejk_load_redcap_01_load(fcfg);

% Fix Surgery Type
sbj_hld = ejk_load_redcap_02_fix_surgery(sbj_hld);

%% Define variables to load
% Demographics
dem_nme = { 'sbj_nme'     'study_id'  'cell' ; ...
            'sbj_scn_dte' 't1_date'   'cell'; ...
            'sbj_grp'     'Group'     'nan' ; ...
            'sbj_inc'     'inclusion' 'nan' ; ...
            'sbj_sex'     'sex'       'cell'; ...
            'sbj_hnd'     'hand'      'cell'; ...
            'sbj_dob'     'dob'       'cell'; ...
            'sbj_age'     'dob'       'cell'; ...
            'sbj_edu'     'educat'    'nan' };

sze_nme = { 'sbj_nme'     'study_id'           'cell'; ...
            'sbj_age_ons' 'age_epil_onset'     'nan'; ...
            'sbj_sze_dur' ''                   'nan'; ...
            'sbj_sze_frq' 'szfreq'             'nan'; ...
            'sbj_sde_ons' 'side_of_epil_focus' 'cell' ; ...
            'sbj_sde_mri' 'mri_lateralization' 'nan' ; ...
            'sbj_mts'     'imaging_mts'        'cell' ; ...
            'sbj_sze_eti' 'epil_etiology'      'nan' ; ...
            'sbj_feb_sze' 'febrileszhx'        'nan' ; ...
            'sbj_aed_num' 'number_aeds'        'nan' ; ...
            'sbj_aed_typ' {'currentaed1' 'currentaed1' 'currentaed2' 'currentaed3' 'currentaed4' 'currentaed5'} 'cell'};

scn_nme = { 'sbj_nme'             'study_id'                'cell'; ...
            'dti_pre_scn_nme'     'dti_visitid_presurg'     'cell'; ...
            'dti_pre_scn_qal'     'dti_overallqa_presurg'   'nan'; ...
            'dti_pre_scn_qal_nte' 'dti_qcnotes_presurg'     'cell'; ...
            'sbj_mr1'             't1_acquired'             'nan'; ...
            'sbj_mr2'             't1_acquired_v2'          'nan'; ...
            'sbj_dt1'             't1_acquired'             'nan'; ...
            'sbj_dt2'             'dti_acquired'            'nan'; ...
            'sbj_frm_b11'         'fmri_block1_acquired'    'nan'; ...
            'sbj_frm_b22'         'fmri_block2_acquired_v2' 'nan'; ...
            'sbj_frm_e11'         'fmri_event1_acquired'    'nan'; ...
            'sbj_frm_e22'         'fmri_event2_acquired_v2' 'nan'; ...
            'sbj_frm_rs1'         'fmri_rs_acquired'        'nan'; ...
            'sbj_frm_rs2'         'fmri_rs_acquired_v2'     'nan'; ...
            'sbj_frm_t21'         't2_acquired'             'nan'; ...
            'sbj_frm_t22'         't2_acquired'             'nan'; ...
            'sbj_frm_ri1'         't2_acquired'             'nan'; ...
            'sbj_frm_ri2'         't2_acquired'             'nan'};
        
cog_nme = { 'sbj_nme'                 'study_id'                        'cell';  ...
            'neu_psy_tst_dte'         'npsych_date'                     'cell'; ...
            'neu_psy_tst_dte_gap'     ''                                'nan'; ...
            'neu_psy_tst_dte_pst'     'post_npsych_date'                'cell'; ...
            'neu_psy_tst_dte_pst_gap' ''                                'nan'  ; ...
            'wms_ver_log_mem'         'wms_version'                     'cell'; ...
            'wms_ver_vpa'             'wms_version'                     'cell'; ...
            'wms_ver_log_mem_pst'     'post_wms_version'                'cell'; ...
            'wms_ver_vpa_pst'         'post_wms_version'                'cell'; ...
            'log_mem_raw_scr_one'     'lm1_recall_raw'                  'nan'; ...
            'log_mem_nor_scr_one'     'lm1_recall_ss'                   'nan'; ...
            'log_mem_raw_scr_one_pst' 'post_lm1_recall_raw'             'nan'; ...
            'log_mem_nor_scr_one_pst' 'post_lm1_recall_ss'              'nan'; ...
            'log_mem_raw_scr_two'     'lm2_raw'                         'nan'; ...
            'log_mem_nor_scr_two'     'lm2_ss'                          'nan'; ...
            'log_mem_raw_scr_two_pst' 'post_lm2_raw'                    'nan'; ...
            'log_mem_nor_scr_two_pst' 'post_lm2_ss'                     'nan'; ...            
            'cvl_tot_raw_scr'         'cvlt_total_raw'                  'nan'; ...
            'cvl_tot_nor_scr'         'cvlt_total_tscore'               'nan'; ...
            'cvl_tot_raw_scr_pst'     'post_cvlt_total_raw'             'nan'; ...
            'cvl_tot_nor_scr_pst'     'post_cvlt_total_tscore'          'nan'; ...  
            'cvl_lfr_raw_scr'         'cvlt_ldfr_raw'                   'nan'; ...
            'cvl_lfr_nor_scr'         'cvlt_ldfr_z'                     'nan'; ...
            'cvl_lfr_raw_scr_pst'     'post_cvlt_ldfr_raw'              'nan'; ...
            'cvl_lfr_nor_scr_pst'     'post_cvlt_ldfr_z'                'nan'; ...
            'vp1_raw_scr'             'vpa1_raw'                        'nan'; ...
            'vp1_nor_scr'             'vpa1_ss'                         'nan'; ...
            'vp1_raw_scr_pst'         'post_vpa1_raw'                   'nan'; ...
            'vp1_nor_scr_pst'         'post_vpa1_ss'                    'nan'; ...
            'vp2_raw_scr'             'vpa2_raw'                        'nan'; ...
            'vp2_nor_scr'             'vpa2_ss'                         'nan'; ...
            'vp2_raw_scr_pst'         'post_vpa2_raw'                   'nan'; ...
            'vp2_nor_scr_pst'         'post_vpa2_ss'                    'nan'; ...
            'bnt_raw_scr'             'bnt_correct'                     'nan'; ...
            'bnt_nor_scr'             'bnt_tscore'                      'nan'; ...
            'bnt_raw_scr_pst'         'post_bnt_correct'                'nan'; ...
            'bnt_nor_scr_pst'         'post_bnt_tscore'                 'nan' ; ...
            'ant_mem_raw_scr'         'ant_total_correct'               'nan' ; ...
            'ant_mem_raw_scr_pst'     'post_ant_total_correct'          'nan' ; ...
            'cat_flu_raw_scr'         'category_fluency_total'          'nan'; ...
            'cat_flu_nor_scr'         'category_fluency_ss'             'nan'; ...
            'cat_flu_raw_scr_pst'     'post_category_fluency_total'     'nan'; ...
            'cat_flu_nor_scr_pst'     'post_category_fluency_ss'        'nan'; ...
            'ltr_tot_raw_scr'         'letter_fluency_total'            'nan'; ...
            'ltr_tot_nor_scr'         'letter_fluency_ss'               'nan'; ...
            'ltr_tot_raw_scr_pst'     'post_letter_fluency_total'       'nan' ; ...
            'ltr_tot_nor_scr_pst'     'post_letter_fluency_ss'          'nan'; ...
            'swt_cor_raw_scr'         'category_switching_correct'      'nan'; ...
            'swt_cor_nor_scr'         'cs_correct_ss'                   'nan'; ...
            'swt_cor_raw_scr_pst'     'post_category_switching_correct' 'nan'; ...
            'swt_cor_nor_scr_pst'     'post_cs_correct_ss'              'nan'; ...
            'swt_acc_raw_scr'         'switching_accuracy'              'nan'; ...
            'swt_acc_nor_scr'         'switching_accuracy_ss'           'nan'; ...
            'swt_acc_raw_scr_pst'     'post_switching_accuracy'         'nan'; ...
            'swt_acc_nor_scr_pst'     'post_switching_accuracy_ss'      'nan'; ...
            'wtr_int_raw_scr'         'wtar_raw'                        'nan'; ...
            'wtr_int_nor_scr'         'wtar_iq'                         'nan'; ...
            'wtr_int_raw_scr_pst'     'post_wtar_raw'                   'nan'; ...
            'wtr_int_nor_scr_pst'     'post_wtar_iq'                    'nan'};
        
emo_nme = { 'sbj_nme' 'study_id'               'cell'; ...
            'bdi'     'bdi'                    'nan'; ...
            'bai'     'beck_anxiety_inventory' 'nan'; ...
            'ndi'     'nddi_e'                 'nan'};

srg_nme = { 'sbj_nme'     'study_id'              'cell'; ...
            'srg_dte'     'date_surgery'          'cell'; ...
            'srg_prf'     'surgery_performed'     'nan'; ...
            'srg_age'     'age_surgery'           'nan'; ...
            'srg_sde'     'resection_side'        'cell'; ...
            'srg_typ'     'surgery_name'          'cell'; ...
            'eng_out'     'y1_simple_engel'       'cell'; ...
            'wda_lng'     'wada_language'         'cell'; ...
            'lng_dom'     'lang_dominance'        'cell' ; ...
            'lng_dom_mth' 'lang_dominance_method' 'cell' };        
        
%% Load Data
sbj_dem = ejk_load_redcap_03_sort_redcap(sbj_hld,dem_nme);
sbj_sze = ejk_load_redcap_03_sort_redcap(sbj_hld,sze_nme);
sbj_scn = ejk_load_redcap_03_sort_redcap(sbj_hld,scn_nme);
sbj_cog = ejk_load_redcap_03_sort_redcap(sbj_hld,cog_nme);
sbj_emo = ejk_load_redcap_03_sort_redcap(sbj_hld,emo_nme);
sbj_srg = ejk_load_redcap_03_sort_redcap(sbj_hld,srg_nme);

%% Additional Calculations
% sbj_dem: Age, Sex,  
sbj_dem = ejk_load_redcap_04_fix_sbj_dem(sbj_dem);

% sbj_sze: Duration, MTS
sbj_sze = ejk_load_redcap_05_fix_sbj_sze(sbj_sze,sbj_dem);

% sbj_cog: Test Interval
sbj_cog = ejk_load_redcap_06_fix_sbj_cog(sbj_cog,sbj_dem,sbj_srg);

% sbj_srg: Surgery
sbj_srg = ejk_load_redcap_07_fix_sbj_srg(sbj_srg);

%% Subset Patients
if isfield(cfg,'sbj_nme')
    sbj_dem = ejk_load_redcap_08_subset(sbj_dem,cfg.sbj_nme);
    sbj_sze = ejk_load_redcap_08_subset(sbj_sze,cfg.sbj_nme);
    sbj_scn = ejk_load_redcap_08_subset(sbj_scn,cfg.sbj_nme);
    sbj_cog = ejk_load_redcap_08_subset(sbj_cog,cfg.sbj_nme);
    sbj_emo = ejk_load_redcap_08_subset(sbj_emo,cfg.sbj_nme);
    sbj_srg = ejk_load_redcap_08_subset(sbj_srg,cfg.sbj_nme);
end











