function vol_bm = abcd_dilate_bm(vol_bm)
%function vol_bm = abcd_dilate_bm(vol_bm)
%
% Created:  11/06/17 by Don Hagler
% Last Mod: 11/06/17 by Don Hagler
%

parms = mmil_args2parms({},{...
  'smooth1',30,[],...
  'thresh1',0.05,[],...
  'smooth2',30,[],...
  'thresh2',0.05,[],...
  'smooth3',0,[],...
  'thresh3',0,[],...  
});

args = mmil_parms2args(parms);
vol_bm = mmil_dilate_mask(vol_bm,args{:});

return;
