language: c
cache:
    - apt
    - ccache
git:
  submodules: false
env:
 global:
    - FLAVOR=linux_ubuntu_16_64
before_install:
    # make sure mysql is running
    - sudo update-rc.d mysql enable
    - sudo service mysql start
    # install build-dependencies as the doc says
    - sudo sh src/other_builds/OS_notes.$FLAVOR
    # install packages needed for testing
    - sudo apt-get install xvfb xauth libgl1-mesa-dri mesa-utils tcsh libjpeg-progs
install:
    - cd src
    - cp Makefile.$FLAVOR Makefile
    - make vastness
script:
    # to gain access to built binaries, include path first
    # (otherwise the wrong `count` binary may be used in the tests)
    - export PATH=$PWD/$FLAVOR:$PATH

