#!/bin/csh

set batchdir = ~/batchdirs/$1
cd $batchdir
mkdir -p pbsout
set joblist = `cat scriptlist.txt`
set qopt = '-q highmem.q -l ccj=1'

foreach job ( $joblist )
  echo $job
  if (-e pbsout/$job.out) then
    rm pbsout/$job.out
  endif
  if (-e pbsout/$job.err) then
    rm pbsout/$job.err
  endif
  echo "qmatjob $batchdir $job" '|' qsub -V $qopt -cwd -N $1_$job -o pbsout/$job.out -e pbsout/$job.err
  echo "qmatjob $batchdir $job" | qsub -V $qopt -cwd -N $1_$job -o pbsout/$job.out -e pbsout/$job.err
  sleep 0.25
end

