#!/bin/csh

set batchdir = ~/batchdirs/$1
cd $batchdir
mkdir -p pbsout
set joblist = `cat scriptlist.txt`

foreach job ( $joblist )
  echo $job
  if (-e pbsout/$job.out) then
    rm pbsout/$job.out
  endif
  if (-e pbsout/$job.err) then
    rm pbsout/$job.err
  endif
  echo "qmat32job $batchdir $job" '|' qsub -V -cwd -N $1_$job -o pbsout/$job.out -e pbsout/$job.err
  echo "qmat32job $batchdir $job" | qsub -V -cwd -N $1_$job -o pbsout/$job.out -e pbsout/$job.err
  sleep 0.25
end

