#!/bin/csh

cd $1
echo "command = " $2
echo "cwd = " `pwd`
echo "HOSTNAME = " $HOSTNAME
echo "JOB_NAME = " $JOB_ID
echo "JOB_NAME = " $JOB_NAME
touch 'pbsout/.isrunning_'$2
mat32 -r "$2"
echo "finished"
mv 'pbsout/.isrunning_'$2 'pbsout/.finished_'$2
