#!/bin/csh

cd $1
echo "command = " $2
echo "cwd = " `pwd`
echo "HOSTNAME = " $HOSTNAME
echo "JOB_NAME = " $JOB_ID
echo "JOB_NAME = " $JOB_NAME
# mat -r "$2"
touch 'pbsout/.isrunning_'$2
mat -r "eval(fileread('${2}.m'))"
echo "finished"
mv 'pbsout/.isrunning_'$2 'pbsout/.finished_'$2
