#!/bin/csh

if ($#argv == 0) then
  echo "ERROR: no batchdir argument supplied"
  exit
endif

set batchdir = ~/batchdirs/$1

if ($#argv > 1) then
  set N = $2
else
  set N = 10
endif

cd $batchdir
mkdir -p pbsout
set joblist = `cat scriptlist.txt`

foreach job ( $joblist )
  echo "############################################################"
  echo running $job
  source $job.csh |& tee pbsout/$job.out
  echo finished
  echo "############################################################"
end

