#!/bin/csh

set job = $1

if (-e pbsout/$job.out) then
  rm pbsout/$job.out
endif
if (-e pbsout/$job.err) then
  rm pbsout/$job.err
endif

touch 'pbsout/.isrunning_'$job
chmod u+x $job.csh
xterm -e $job.csh -logfile pbsout/$job.out
echo "finished" >> pbsout/$job.out
mv 'pbsout/.isrunning_'$job 'pbsout/.finished_'$job

