#! /bin/csh -f

set sys = `uname -s`
if ($argv == "") then
  echo "mk <target>       [sys=$sys]"
  exit
endif

if ($sys == "IRIX")   make -f Makefile-IRIX-cc  "$argv"
if ($sys == "IRIX64") make -f Makefile-IRIX-cc  "$argv"
if ($sys == "Linux")  make -f Makefile-Linux-cc "$argv"

