function iSASZ_utah_eff(fcfg)

fprintf([fcfg.sbj_nme ': Starting iSASZ_pap_eff_hgp_act on %s \n'],fcfg.sbj_nme)

cfg = [];
cfg.load    = 'yes';
cfg.file    = [fcfg.dat_fld '/' fcfg.sbj_nme '_overall_data.mat'];
bcc_dat     = ft_func([],cfg);

for iF = 1:numel(bcc_dat.data_name);
    bcc_dat.(bcc_dat.data_name{iF}).cfg.alt_lab.stt_lab = bcc_dat.(bcc_dat.data_name{iF}).label;
    bcc_dat.(bcc_dat.data_name{iF}).cfg.alt_lab.label = bcc_dat.(bcc_dat.data_name{iF}).label;
end

%% Visual Responsive Electrodes
eve_typ = unique(bcc_dat.(bcc_dat.data_name{1}).cfg.alt_eve.trialinfo);

cfg = [];

cfg.ovr_wrt = 1;
cfg.clr_fld = fcfg.clr_fld;

cfg.data_name = 1;

cfg.stt_lab = 'stt_lab';

cfg.alt_stt = { 'vis_new_ovr_stt' ...
                'aud_new_ovr_stt' ...
                'vis_new_old_stt' ...
                'aud_new_old_stt' ...
                'vis_frq_stt' ...
                'aud_frq_stt' };
cfg.cmp_trl = { 'ovr' ...
                'ovr' ...
                'vis_new_old' ...
                'aud_new_old' ...
                'vis_frq_med' ...
                'aud_frq_med' };
cfg.cmp_stt = { [ 1 ] ...
                [ 2 ] ...
                [ 3 ] ...
                [ 4 ] ...
                [ 5 ] ...
                [ 6 ] };
cfg.cmp_nme = { { 'vis_ovr_1000ms' } ...
                { 'aud_ovr_1000ms' } ...
                { 'vis_rep_1000ms' } ...
                { 'aud_rep_1000ms' } ...
                { 'vis_lex_1000ms' } ...
                { 'aud_lex_1000ms' } };
cfg.cmp     = { { '101>999' } ...
                { '201>999' } ...
                { '111>112' } ...
                { '211>212' } ...
                { '151>152' } ...
                { '251>252' } };
cfg.tme_win = { { [0.025 1.000] } ...
                { [0.025 1.000] } ...
                { [0.025 1.000] } ...
                { [0.025 1.000] } ...
                { [0.025 1.000] } ...
                { [0.025 1.000] } };
cfg.stt_col = { { 'bright red' } ...
                { 'bright red' } ...
                { 'bright red' } ...
                { 'bright red' } ...
                { 'bright red' } ...
                { 'bright red' } };

cfg.sbj_nme  = fcfg.sbj_nme;
cfg.typ      = cellfun(@(x) x(end-2:end),bcc_dat.data_name(cfg.data_name),'uni',0);
if any(strcmpi(cfg.typ,'uth_cmb')); cfg.typ(strcmpi(cfg.typ,'hlb')) = {'hgp'}; end
cfg.specific = {'typ' ; 1:numel(cfg.typ)};

dat          = ft_func(@mmil_chn_eff,cfg,bcc_dat);

end