function [arg_groups,extra_tags,strip_flag] = mmil_args_MEG_MMIL_Sensor_GroupAvg()
%function [arg_groups,extra_tags,strip_flag] = mmil_args_MEG_MMIL_Sensor_GroupAvg()
%
% Purpose: for use with MMIL_Args in selecting context relevant parameters
%   from parameter struct arrays (e.g. parms, ProjInfo)
%
% Output:
%   arg_groups: cell array of fieldname prefixes (e.g. 'BOLD', 'PROC', etc.)
%     specifying group of parameter names
%   extra_tags: cell array of parameter names
%   strip_flag: [0|1] whether arg_group prefixes should be stripped from
%     final parameter names
%
% Created:  09/17/13 by Don Hagler
% Last Mod: 09/17/13 by Don Hagler
%

arg_groups = [];
extra_tags = {...
  'StudyInfo'...
  'RootDirs'...
  'outdir'...
  'outstem'...
  'proc_prefix'...
  'proc_infix'...
  'conditions'...
  'condition_names'...
  'usegrad_flag'...
  'usemag_flag'...
  'useEEG_flag'...
  'grad_scalefact'...
  'mag_scalefact'...
  'EEG_scalefact'...
  'channames'...
  'power_flag'...
  'norm_flag'...
  'time'...
  't0'...
  't1'...
  'samp_dur'...
  'baseline_flag'...
  'baseline_t0'...
  'baseline_t1'...
  'qcflag'...
  'forceflag'...
  ...
  'required_containers'...
};
strip_flag = 0;




