function [arg_groups,extra_tags,strip_flag] = mmil_args_ts_process_fif_data()
%function [arg_groups,extra_tags,strip_flag] = mmil_args_ts_process_fif_data()
%
% Purpose: for use with MMIL_Args in selecting context relevant parameters
%   from parameter struct arrays (e.g. parms, ProjInfo)
%
% Output:
%   arg_groups: cell array of fieldname prefixes (e.g. 'BOLD', 'PROC', etc.)
%     specifying group of parameter names
%   extra_tags: cell array of parameter names
%   strip_flag: [0|1] whether arg_group prefixes should be stripped from
%     final parameter names
%
% Created:  10/25/11 by Don Hagler
% Last Mod: 10/25/11 by Don Hagler
%

arg_groups = [];
extra_tags = {
  'rootoutdir'...
  'prefix'...
  'browseraw'...
  'saveepochs_flag'...
  'write_fif_flag'...
  'fifname_evcode_flag'...
  'trigchan'...
  'events_fnames'...
  'evcode_offset'...
  'valid_event_codes'...
  'event_recode_rules'...
  'code_excl'...
  'time_excl_pre'...
  'time_excl_post'...
  'trig_minduration'...
  'max_num_trials'...
  'stim_delay'...
  'prestim_dur'...
  'poststim_dur'...
  'reject_mag'...
  'reject_grad'...
  'reject_eeg'...
  'reject_eog'...
  'bandpass_flag'...
  'bandpass_low_cf'...
  'bandpass_low_tb'...
  'bandpass_high_cf'...
  'bandpass_high_tb'...
  'notch_flag'...
  'notch_cf'...
  'notch_tb'...
  'dsfact'...
  'detrend_flag'...
  'baseline_flag'...
  'baseline_start'...
  'baseline_end'...
  'ncov_ex_evnts'...
  'badchans'...
  'badchanfile'...
  'readtrans_flag'...
  'post_subnull_flag'...
  'null_event'...
  'post_combcond_flag'...
  'post_combcond_append_flag'...
  'fname_combcond_info'...
  'post_bandpass_flag'...
  'post_notch_flag'...
  'post_dsfact'...
  'post_detrend_flag'...
  'post_baseline_flag'...
  'post_stim_delay'...
  'post_badchans'...
  'post_badchanfile'...
  'post_rm_badchans_flag'...
  'ICA_auto_flag'...
  'ICA_manual_flag'...
  'ICA_ref_chan'...
  'ICA_chantype'...
  'ICA_maxsteps'...
  'ICA_ntrial'...
  'ICA_ncomponents'...
  'ICA_rescale_flag'...
  'ICA_sorttrials'...
  'forceflag'...
	'saveperevent'...
  'datatype'...
};
strip_flag = 0;

