function [arg_groups,extra_tags,strip_flag] = mmil_args_ABCD_Analyze_rsBOLD_Exams()
%function [arg_groups,extra_tags,strip_flag] = mmil_args_ABCD_Analyze_rsBOLD_Exams()
%
% Purpose: for use with MMIL_Args in selecting context relevant parameters
%   from parameter struct arrays (e.g. parms, ProjInfo)
%
% Output:
%   arg_groups: cell array of fieldname prefixes (e.g. 'BOLD', 'PROC', etc.)
%     specifying group of parameter names
%   extra_tags: cell array of parameter names
%   strip_flag: [0|1] whether arg_group prefixes should be stripped from
%     final parameter names
%
% Created:  07/05/17 by Don Hagler
% Last Mod: 07/05/17 by Don Hagler
%

arg_groups = {};
extra_tags = {'StudyInfo' 'RootDirs' 'batchname'...
  'fname_info' 'SeriesType' 'qcflag' 'verbose' 'forceflag' 'outdir' 'outstem'...
  'snums' 'snums_valid' 'infix' 'revflag' 'min_numTRs' 'max_nscans'...
  'mc_flag' 'mc_bandpass_flag' 'motion_absflag' 'mask_flag' 'mask_thresh'...
  'norm_flag' 'normval' 'thresh' 'detrend' 'skipTRs'...
  'bandpass_flag' 'bandpass_low' 'bandpass_high' 'bandpass_tb' 'bandpass_zpad_flag'...
  'wm_flag' 'wm_codes' 'wm_erode_flag' 'wm_erode_nvoxels'...
  'csf_flag' 'csf_codes' 'csf_erode_flag' 'csf_erode_nvoxels'...
  'brain_flag' 'brain_codes' 'brain_erode_flag' 'brain_erode_nvoxels'...
  'deriv_flag' 'projfrac_flag' 'projdist' 'projfrac' 'projdist_avg' 'projfrac_avg'...
  'mask_midbrain_flag' 'surfname'...
  'ico_flag' 'ico_order' 'ico_trunc_flag' 'ico_presmooth'...
  'roi_outfix' 'aparc_flag' 'fnames_aparc' 'fparc_flag' 'fnames_fparc'...
  'fname_points' 'aseg_flag' 'aseg_erode_flag' 'aseg_erode_nvoxels'...
  'fname_aseg' 'csv_tseries_flag' 'aseg_roilist'...
  'corr_outfix' 'corr_seed_roinames' 'corr_roi_flag' 'corr_roi_ico_flag'...
  'corr_roi_ico_maps_flag' 'corr_ico_flag' 'required_containers' 'modality'...
  'QC_raw' 'QC_BOLD' 'QC_recon' 'skipTRs_GE' 'skipTRs_Philips' 'skipTRs_Siemens'};
strip_flag = 0;


