function [arg_groups,extra_tags,strip_flag] = mmil_args_ABCD_Analyze_taskBOLD_Exams()
%function [arg_groups,extra_tags,strip_flag] = mmil_args_ABCD_Analyze_taskBOLD_Exams()
%
% Purpose: for use with MMIL_Args in selecting context relevant parameters
%   from parameter struct arrays (e.g. parms, ProjInfo)
%
% Output:
%   arg_groups: cell array of fieldname prefixes (e.g. 'BOLD', 'PROC', etc.)
%     specifying group of parameter names
%   extra_tags: cell array of parameter names
%   strip_flag: [0|1] whether arg_group prefixes should be stripped from
%     final parameter names
%
% Created:  12/02/16 by Don Hagler
% Last Mod: 09/07/17 by Don Hagler
%

arg_groups = {};
extra_tags = {'StudyInfo' 'RootDirs' 'batchname' 'fname_info' ...
  'force_eprime_flag' 'eprime_rootdir' 'eprime_indir' 'qcflag' 'forceflag'...
  'tasknames' 'infix' 'mc_flag' 'mc_inter_flag'...
  'analysis_prefix' 'analysis_outfix' 'stim_times_flag'...
  'stim_times_model' ' stim_times_nbasis'...
  'concat_flag' 'pthresh' 'contrasts_flag' 'iresp_flag'...
  'regFS_flag' 'paint_flag' 'aseg_flag' 'aseg_erode_flag' 'aseg_erode_nvoxels'...
  'fname_aseg' 'aparc_flag' 'fnames_aparc' 'render_flag' 'projdist' ...
  'projfract' 'projfrac_flag' 'projdist_avg' 'resamp_flag'...
  'force_repaint_flag' 'surfname' 'mask_midbrain_flag' 'sphere_flag'...
  ...
  'snums' 'snums_valid' 'skipTRs' 'minlag' 'maxlag'... 
  'curvflag' 'curvfact' 'zoom' 'tif_flag' 'tif_dpi'...
  'fmin' 'fmid' 'fmax' 'view_surfname' 'viewlist'  'ant'...
  'stim_fnames' 'smoothsteps' 'sphsmoothsteps'...
  'required_containers' 'modality' 'QC_raw' 'QC_BOLD' 'QC_recon'...
  'skipTRs_GE' 'skipTRs_Philips' 'skipTRs_Siemens'};
strip_flag = 0;

