function [arg_groups,extra_tags,strip_flag] = mmil_args_rc_RCSE()
%function [arg_groups,extra_tags,strip_flag] = mmil_args_rc_RCSE()
%
% Purpose: for use with MMIL_Args in selecting context relevant parameters
%   from parameter struct arrays (e.g. parms, ProjInfo)
%
% Output:
%   arg_groups: cell array of fieldname prefixes (e.g. 'BOLD', 'PROC', etc.)
%     specifying group of parameter names
%   extra_tags: cell array of parameter names
%   strip_flag: [0|1] whether arg_group prefixes should be stripped from
%     final parameter names
%
% Created:  07/11/11 by Don Hagler
% Last Mod: 11/01/13 by Don Hagler
%

arg_groups = [];
extra_tags = {'prefix' 'infix' 'infix_flag' 'rootoutdir' 'datamatfile'...
 'subjdir' 'plotflag' 'transfile' 'badchanfile' 'forward_matfile'...
 'indy_locs_flag' 'graymid_flag' 'calc_dipinfo_flag' 'inverse_type'...
 'ncov_type' 'SNR' 'forceflag' 'retfit_dir' 'retfit_stem' 'vf2ctx_flag'...
 'stim_type' 'use_areas' 'r_offset' 'th_offset' 'r_max' 'ecc_width'...
 'theta_width' 'w_thresh' 'single_vertex_flag' 'rf_sizes' 'rf_slopes'...
 'restrict_hemi_flag' 'restrict_uplow_flag' 'restrict_flag'...
 'retfit_data_flag' 'fstem_conds' 'cond_offsets_flag' 'hemivec' 'uplowvec'...
 'eccvec' 'thetavec' 'contvec' 'sfvec' 'colvec' 'polarity_penalty'...
 'fit_range_flag' 'fit_time0' 'fit_time1' 'offset_niters' 'max_offset_niters'...
 'offset_mstarts' 'mstart_rotsearch_flag' 'mstart_rfsearch_flag'...
 'mstart_randstart_flag' 'mstart_average_flag' 'reweight_flag'...
 'reweight_factor' 'reweight_maxiter' 'reweight_tol' 'reweight_leverage_flag'...
 'reweight_leverage_max_flag' 'hybrid_flag' 'hybrid_pre_niters'...
 'offset_niters_last' 'offset_group_flag' 'offset_group_patches_flag'...
 'offset_group_areas_flag' 'offset_const_areas' 'r_step' 'th_step'...
 'r_offset_range' 'th_offset_range' 'grid_offset_flag' 'grid_offset_smooth'...
 'rot_niters' 'rot_step' 'rot_max' 'best_rot' 'rscale_niters' 'rscale_step'...
 'rscale_range' 'best_rscale' 'nbrhd_niters' 'nbrhd_full_flag' 'prior_prefix'...
 'prior_weight' 'prior_avg_flag' 'prior_mindiff_flag' 'prior_indy_wform_flag'...
 'corr_time0' 'corr_time1' 'best_retmap_prefix' 'err_prefix' 'rf_niters'...
 'rf_min_sizes' 'rf_max_sizes' 'rf_min_slopes' 'rf_max_slopes' 'rf_size_step'...
 'rf_slope_step' 'calc_scalefacts_flag' 'bem_flag' 'conductivities'...
 'EEG_gain_scalefact' 'nlayers' 'bem_surf_files' 'usegrad_flag'...
 'usemag_flag' 'useEEG_flag' 'indy_smfact' 'ecc_smfact' 'upperlower_smfact'...
 'hemi_smfact' 'loose_flag' 'loose_tang_weight' 'condF_thresh' 'dip_matfile'...
 'ret_dips_lh_dec_file' 'ret_dips_rh_dec_file' 'ret_dip_qfield_flag'...
 'nonret_dips_lh_dec_file' 'nonret_dips_rh_dec_file' 'ret_dips_weight'...
 'nonret_dips_weight' 'norm_weights_flag' 'area_names' 'plot_outdir'...
 'plot_normflag' 'plot_ylim' 'save_avg_flag' 'write_err_flag'...
 'write_fit_flag' 'write_areafit_flag' 'write_fif_flag' 'template_fif'...
 'fmincon_flag'...
};
strip_flag = 0;

