function [arg_groups,extra_tags,strip_flag] = mmil_args_MEG_MMIL_GroupRCSE()
%function [arg_groups,extra_tags,strip_flag] = mmil_args_MEG_MMIL_GroupRCSE()
%
% Purpose: for use with MMIL_Args in selecting context relevant parameters
%   from parameter struct arrays (e.g. parms, ProjInfo)
%
% Output:
%   arg_groups: cell array of fieldname prefixes (e.g. 'BOLD', 'PROC', etc.)
%     specifying group of parameter names
%   extra_tags: cell array of parameter names
%   strip_flag: [0|1] whether arg_group prefixes should be stripped from
%     final parameter names
%
% Created:  03/23/11 by Don Hagler
% Last Mod: 04/15/12 by Don Hagler
%

arg_groups = [];
extra_tags = {'StudyInfo' 'RootDirs' 'RCSE_prefix' 'RCSE_infix'...
  'RCSE_infix_flag' 'RCSE_fstem_conds' 'hiC_flag'...
  'reweight_flag' 'reweight_init_flag' 'reweight_factor'...
  'inverse_type' 'SNR'...
  'resamp_flag' 'resamp_niters' 'randseed_flag'...
  'fill_err_flag' 'ci_tail'...
  'outdir' 'outstem'...
  'qcflag' 'plotflag' 'forceflag'...
  'smooth_sigma' 'auc_range' 'auc_nbins'...
  'auc_baseline_flag' 'auc_baseline_range' 'peak_range' 'peak_pol'...
  'peak_mindiff' 'normflag' 'powerflag' 'firstflag'...
  'sfreq' 't0' 't1' 'time'...
  'condition_values' 'condition_label' 'eps_flag' 'visible_flag'...
  'linewidth' 'min_linewidth' 'max_linewidth' 'fontname'...
  'fontsize' 'ylim_auc' 'ylim_peak' 'ylim_latency'...
  'ylim_wform' 'xlim' 'units_wform' 'logx_flag'...
  'stderrflag' 'area_names' 'area_colors' 'legend_loc'...
  'label_flag' 'reweight_maxiter' 'reweight_tol'...
  'reweight_leverage_flag' 'reweight_leverage_max_flag'...
  'plot_text_dx' 'plot_text_dy' 'required_containers'  ...
};
strip_flag = 0;



