function mmil_summarize_serinfo(SeriesInfo,fname,forceflag)
%function mmil_summarize_serinfo(SeriesInfo,[fname],[forceflag])
%
% Purpose: create csv file spreadsheet with summary of SeriesInfo
%
% Required Input:
%   SeriesInfo: struct array containing classified series information
%
% Optional Input:
%   fname: name of output spreadsheet
%     {default = 'SeriesInfo.csv'}
%   forceflag: overwrite existing output
%     {default = 0}
%
% Created:  11/14/12 by Don Hagler
% Last Mod: 11/16/12 by Don Hagler
%

if ~mmil_check_nargs(nargin,1), return; end;

if ~exist('fname','var') || isempty(fname)
  fname = [pwd '/SeriesInfo.csv'];
end;
if ~exist('forceflag','var') || isempty(forceflag), forceflag = 0; end;

if exist(fname,'file') && ~forceflag, return; end;

% fields to be saved in csv file
serinfo_tags = {...
  'SeriesNumber',...
  'SeriesType',...
  'SeriesDate',...
  'SeriesTime',...
  'SeriesDescription',...
  'Manufacturer',...
  'SequenceName',...
  'ScanningSequence',...
  'SequenceVariant'...
  'SequenceLabel',...
  'ScanOptions',...
  'ImagesInAcquisition',...
  'AcquisitionRows',...
  'AcquisitionColumns',...
  'Rows',...
  'Columns',...
  'nslices',...
  'XPixelSpacing',...
  'YPixelSpacing',...
  'SliceThickness',...
  'NumberOfPhaseEncodingSteps',...
  'InPlanePhaseEncodingDirection',...
  'readoutFOV',...
  'phaseFOV',...
  'FlipAngle',...
  'RepetitionTime',...
  'InversionTime',...
  'EchoTime',...
  'ImageType',...
  'MRAcquisitionType',...
  'ReceiveCoilName',...
  'PixelBandwidth',...
  'NumberOfAverages',...
  'ndiffdirs',...
  'nb0',...
  'bval',...
  'pepolar',...
  'EchoSpacing',...
  'slice_tpattern',...
};

outdir = fileparts(fname);
if ~isempty(outdir), mmil_mkdir(outdir); end;

fid = fopen(fname,'wt');
if fid==-1
  error('failed to open file %s for writing',fname);
end;
fprintf(fid,'"SeriesIndex","SeriesDirName",');
for f=1:length(serinfo_tags)
  fprintf(fid,'"%s"',serinfo_tags{f});
  if f==length(serinfo_tags)
    fprintf(fid,'\n');
  else
    fprintf(fid,',');
  end;
end;
for s=1:length(SeriesInfo)
  fprintf(fid,'%d,',s);
  tmpinfo = SeriesInfo(s);
  [tmp,SeriesDirName] = fileparts(tmpinfo.SeriesDirPath);
  fprintf(fid,'"%s",',SeriesDirName);
  for f=1:length(serinfo_tags)
    if isfield(tmpinfo,serinfo_tags{f})
      val = getfield(tmpinfo,serinfo_tags{f});
      if ischar(val)
        fprintf(fid,'"%s"',val);
      elseif isnumeric(val) & length(val)>1
        fprintf(fid,'"multiple"');
      elseif isnumeric(val) & val==int64(val)
        fprintf(fid,'%d',val);
      elseif isfloat(val)
        fprintf(fid,'%f',val);
      end;
    end;
    if f==length(serinfo_tags)
      fprintf(fid,'\n');
    else
      fprintf(fid,',');
    end;
  end;
end;
fclose(fid);

