function RootDirs = MMIL_RootDirs_from_ProjInfo(ProjInfo)
%function RootDirs = MMIL_RootDirs_from_ProjInfo(ProjInfo)
%
% Required Parameters:
%   ProjInfo: Project Info struct array
%
% Output:
%   RootDirs: struct containing locations of data directories
%
% Created:  09/18/10 by Don Hagler
% Last Mod: 03/01/17 by Don Hagler
%

if ~mmil_check_nargs(nargin,1), return; end;

rootdir_names = {...
'incoming'...
'unpack'...
'orig'...
'pc'...
'qc'...
'raw'...
'proc'...
'proc_dti'...
'proc_bold'...
'fsurf'...
'fsico'...
'fslong'...
'raw_asl'...
'proc_asl'...
'long'...
'long_dti'...
'orig_pet'...
'orig_pet_pib'...
'raw_pet'...
'proc_pet'...
'orig_meg'...
'raw_meg'...
'proc_meg'...
'fiberdir'
};

for r=1:length(rootdir_names)
  tmp = mmil_getfield(ProjInfo,rootdir_names{r},[]);
  RootDirs.(rootdir_names{r}) = tmp;
end;
RootDirs = MMIL_Check_RootDirs(RootDirs);

