function FW_effects_word_char_lfp(fcfg)

fprintf([fcfg.sbj_nme ': Starting initial effects work on %s \n'],fcfg.sbj_nme)

cfg = [];
cfg.load    = 'yes';
cfg.file    = [fcfg.dat_fld '/' fcfg.sbj_nme '_overall_data.mat'];
bcc_dat     = ft_func([],cfg);

for iF = 1:numel(bcc_dat.data_name); 
    bcc_dat.(bcc_dat.data_name{iF}).cfg.alt_lab.stt_lab = bcc_dat.(bcc_dat.data_name{iF}).label; 
    bcc_dat.(bcc_dat.data_name{iF}).cfg.alt_lab.label = bcc_dat.(bcc_dat.data_name{iF}).label;
end

%% Orthographic Effects
cfg = [];
cfg.ovr_wrt = 1;
cfg.clr_fld = fcfg.clr_fld;

cfg.data_name = 1;

cfg.stt_lab = 'stt_lab';

cfg.alt_stt = { 'vis_wrd_lng' ... 
                'vis_wrd_lng_big' ...
                'vis_wrd_lng_frq' ... 
                'vis_wrd_lng_ngh' ...
                'vis_wrd_big' ... 
                'vis_wrd_big_lng' ...
                'vis_wrd_big_frq' ... 
                'vis_wrd_big_ngh' ...
                'vis_wrd_frq' ... 
                'vis_wrd_frq_lng' ...
                'vis_wrd_frq_big' ... 
                'vis_wrd_frq_ngh' ...
                'vis_wrd_ngh' ... 
                'vis_wrd_ngh_lng' ...
                'vis_wrd_ngh_big' ...
                'vis_wrd_ngh_frq' };
cfg.cmp_trl = { 'wrd_lng_med' ... 
                'wrd_lng_med_crr_by_wrd_big' ...
                'wrd_lng_med_crr_by_wrd_frq' ...
                'wrd_lng_med_crr_by_wrd_ngh' ...
                'wrd_big_med' ...
                'wrd_big_med_crr_by_wrd_lng' ...
                'wrd_big_med_crr_by_wrd_frq' ...
                'wrd_big_med_crr_by_wrd_ngh' ...
                'wrd_frq_med' ...
                'wrd_frq_med_crr_by_wrd_lng' ...
                'wrd_frq_med_crr_by_wrd_big' ...
                'wrd_frq_med_crr_by_wrd_ngh' ...
                'wrd_ngh_med' ...
                'wrd_ngh_med_crr_by_wrd_lng' ...
                'wrd_ngh_med_crr_by_wrd_big' ...
                'wrd_ngh_med_crr_by_wrd_frq' };
cfg.cmp_stt = { [ 1 ] ... 
                [ 2 ] ...
                [ 3 ] ... 
                [ 4 ] ...
                [ 5 ] ... 
                [ 6 ] ...
                [ 7 ] ... 
                [ 8 ] ...
                [ 9 ] ... 
                [ 10 ] ...
                [ 11 ] ... 
                [ 12 ] ...
                [ 13 ] ... 
                [ 14 ] ...
                [ 15 ] ... 
                [ 16 ] };
cfg.cmp_nme = { { 'LngSensitive' } ; ... 
                { 'LngSensitive' } ; ...
                { 'LngSensitive' } ; ... 
                { 'LngSensitive' } ; ...
                { 'BigSensitive' } ; ... 
                { 'BigSensitive' } ; ...
                { 'BigSensitive' } ; ... 
                { 'BigSensitive' } ; ...
                { 'FrqSensitive' } ; ...
                { 'FrqSensitive' } ; ...
                { 'FrqSensitive' } ; ...
                { 'FrqSensitive' } ; ...
                { 'NghSensitive' } ; ...
                { 'NghSensitive' } ; ...
                { 'NghSensitive' } ; ...
                { 'NghSensitive' } };
cfg.cmp     = { { '111!112' } ... 
                { '111!112' } ...
                { '111!112' } ... 
                { '111!112' } ...
                { '141!142' } ... 
                { '141!142' } ...
                { '141!142' } ... 
                { '141!142' } ...
                { '121!122' } ... 
                { '121!122' } ...
                { '121!122' } ... 
                { '121!122' } ...
                { '131!132' } ... 
                { '131!132' } ...
                { '131!132' } ... 
                { '131!132' } };
cfg.tme_win = { { [0.025 0.600] } ... 
                { [0.025 0.600] } ...
                { [0.025 0.600] } ... 
                { [0.025 0.600] } ...
                { [0.025 0.600] } ... 
                { [0.025 0.600] } ...
                { [0.025 0.600] } ... 
                { [0.025 0.600] } ...
                { [0.025 0.600] } ... 
                { [0.025 0.600] } ...
                { [0.025 0.600] } ... 
                { [0.025 0.600] } ...
                { [0.025 0.600] } ... 
                { [0.025 0.600] } ...
                { [0.025 0.600] } ... 
                { [0.025 0.600] } };
cfg.stt_col = { { '' } ... 
                { '' } ...
                { '' } ... 
                { '' } ...
                { '' } ... 
                { '' } ...
                { '' } ... 
                { '' } ...
                { '' } ... 
                { '' } ...
                { '' } ... 
                { '' } ...
                { '' } ... 
                { '' } ...
                { '' } ... 
                { '' } };
           
cfg.sbj_nme  = fcfg.sbj_nme;
cfg.typ      = cellfun(@(x) x(end-2:end),bcc_dat.data_name(cfg.data_name),'uni',0);
if any(strcmpi(cfg.typ,'hlb')); cfg.typ(strcmpi(cfg.typ,'hlb')) = {'hgp'}; end
cfg.specific = {'typ' ; 1:numel(cfg.typ)};

dat          = ft_func(@mmil_chn_eff,cfg,bcc_dat);

% Split effects into ecog/depth
cfg = [];

cfg.sbj_nme = fcfg.sbj_nme;
cfg.clr_fld = fcfg.clr_fld;

cfg.dat_typ = {'lfp'};

mmil_split_stat(cfg);

% Split timing into ecog/depth
cfg = [];

cfg.sbj_nme = fcfg.sbj_nme;
cfg.clr_fld = fcfg.clr_fld;

cfg.dat_typ = {'lfp'};

mmil_split_timing(cfg);

end